aggregation_params:
  trans_back_aggreg_list: [1, 3, 6, 9, 12]
data_set:
  oot: 50000
  train: 0.7
  test: 0.2
  valid: 0.1
hp_params:
  target: 'default'
  hp_number_of_experiments: 200
  holdout_set_prc: 0.33
  learning_rate: [0.001, 0.5]
  max_bin: [100, 10000]
  max_depth: [2, 25]
  min_data_in_leaf: [10, 150]
  num_leaves: [10, 300]
  lambda_l1: [0.0, 0.5]
  lambda_l2: [0.0, 2.0]
  bagging_fraction: [0.3, 1.0]
  bagging_freq: [1, 10]
  feature_fraction: [0.3, 1.0]
  num_boost_round: 300
  verbose_eval: False
  early_stopping_rounds: 15